### ISSUE TITLE
requirements.txt is empty

### ISSUE THREAD

**Issue by SingCheng** [YingchaojieFeng/PromptMagician#1]
Hi,

Since your requirements.txt is empty, could you please let us know which python packages needed?

Cheers,

Po

**Comment by YingchaojieFeng** [comment]
Hi, thank you for the feedback! 
We will update the requirements.txt in the coming days.

**Comment by YingchaojieFeng** [comment]
We have updated requirements.txt to list the Python packages needed.

**Comment by SingCheng** [comment]
> We have updated requirements.txt to list the Python packages needed.

Thank you
